name: Deployment Workflow
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ssh connection
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.IP }}
        username: amaccormack
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          killall screen
          cd telegram-reubot
          git pull
          source venv/bin/activate
          pip install -r requirements.txt
          screen -dm python main.py
